services:
  - type: web
    name: seo-blog-generator
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start_render.sh"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
      - key: DJANGO_SETTINGS_MODULE
        value: blog_generator.settings_production
      - key: DEBUG
        value: "False"
    # Auto-deploy when you push to main branch
    autoDeploy: true
